### ISSUE TITLE
About Vivalas Loop

### ISSUE THREAD

**Issue by flying1574** [dp770/aws_deepracer_worksheet#15]
1

**Comment by dp770** [comment]
Sure @flying1574 . What’s the question?

**Comment by flying1574** [comment]
can you give me your real-time com vivalas Loop reward function Specific parameters

**Comment by flying1574** [comment]
Hello,I attend the "AWS Student Deepracer",and I am "Compete in the AWS
DeepRacer Student League",[image: image.png],,
In here,only change the Parameter
[image: image.png],

So can you give me a best Reward_function?And explain it?
Thank you

dp770 ***@***.***> 于2022年1月12日周三 08:01写道：

**Comment by flying1574** [comment]
Can we talk?I just want Vivalas Loop Reward function

**Comment by dp770** [comment]
Hi Lei Feng,

 

The reward function which is located here https://github.com/dp770/aws_deepracer_worksheet/blob/main/src/reward_function.py is flexible to the extend that you can adjust it’s parameters to your needs. Obviously, there is always room for improvements, so feel free to contribute.

 

With regards to “best parameters” for the Vivalas Loop track, there is a number of model parameters you can play with to find what works best for you.

1.	First, you can adjust racing line to your needs. However, I’ll suggest to steek to the default ones for “Racing Line v1”, which are:

RACING_LINE_SMOOTHING_STEPS = 1     # Track specific. Critical to keep in sync with optimal racing line

RACING_LINE_VS_CENTRAL_LINE = 0.90  # Number in range of [0, 1]. Zero forces to follow central line, 1 - racing line

 

2.	Secondly, depending on the training stage of your model, you might want to give more flexibility to the car at the beginning (i.e. give some reward for non-favourite  exploration) so it learns to complete the track, then tighten these parameters to force it follow only racing line. For this you can use, alongside other already available (read comments in reward_function.py <https://github.com/dp770/aws_deepracer_worksheet/blob/main/src/reward_function.py> ):

RACING_LINE_SMOOTHING_STEPS = 1     # Track specific. Critical to keep in sync with optimal racing line

RACING_LINE_WIDTH_FREE_ZONE = 0.10  # Percentage of racing line width for 100% of "being on track" reward

RACING_LINE_WIDTH_SAFE_ZONE = 0.25  # Percentage of racing line width for distance relative "being on track" reward

 

3.	Third, you should explore how reward allocation parameters can help you to force the car to finish the track as fast as possible. Remember, there is be always a trade-off between speed and stability of your model. Play with following parameters to explore this:

REWARD_WEIGHT_PROG_STEP = 35

REWARD_WEIGHT_EXP_SPEED = 25

REWARD_WEIGHT_DIR_STEER = 20

REWARD_WEIGHT_ON_TRACK = 15

 

 

Hope this helps.

**Comment by dp770** [comment]
I suppose there are no additional questions at the moment. So, I'm closing this issue.
